name: blood_donation_app
description: "A Flutter app that connects blood donors with those in need."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.2
  http: ^1.3.0
  shared_preferences: ^2.3.1
  geolocator: ^13.0.2
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.3.0
  onesignal_flutter: ^5.3.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  get: ^4.7.2
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  calendar_date_picker2: ^2.0.0
  flutter_facebook_auth: ^7.1.2
  # flutter_login_facebook: ^2.0.1
  # cached_network_image: ^3.4.1
  # google_sign_in: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
